#!/bin/sh

export TARA_CONNECTOR_ADDRESS=${TARA_CONNECTOR_ADDRESS:="0x98C860E92486975d93A4b83261315c02728Add43"}
export ETH_CONNECTOR_ADDRESS=${ETH_CONNECTOR_ADDRESS:="0x6B404ccd2AEa5B06F00a4f3565fE88Ed1fD7A07E"}
export TARA_ERC20_MINTING_CONNECTOR_ADDRESS=${TARA_ERC20_MINTING_CONNECTOR_ADDRESS:="0x6aA8f4644bAa008e1fD6A81d31aCCC1cCf13e339"}
export ETH_ERC20_MINTING_CONNECTOR_ADDRESS=${ETH_ERC20_MINTING_CONNECTOR_ADDRESS:="0x030f4671e48Fc2a0eE4BdA956B2Aba26F5b7F8A9"}
export ETH_BRIDGE_ADDRESS=${ETH_BRIDGE_ADDRESS:="0xe67957f965b3cb5c58abF0309D9a8e98787Ab75e"}
export TARA_BRIDGE_ADDRESS=${TARA_BRIDGE_ADDRESS:="0xcAF2b453FE8382a4B8110356DF0508f6d71F22BF"}
export WTARA_TOKEN_ADDRESS=${WTARA_TOKEN_ADDRESS:="0x09A77e9b4a8E96Fe874A88229a95BC69Bc2e05F9"}
export WETH_TOKEN_ADDRESS=${WETH_TOKEN_ADDRESS:="0xdB0698D2c8FbE2C3c36941ccEC488834BbcAf151"}
export ETHEREUM_GRAPHQL_API=${ETHEREUM_GRAPHQL_API:="https://indexer.devnet.taraxa.io/subgraphs/name/bridge/ethereum"}
export TARAXA_GRAPHQL_API=${TARAXA_GRAPHQL_API:="https://indexer.devnet.taraxa.io/subgraphs/name/bridge/taraxa"}

export STATIC_FOLDER="/app/.next"

echo "Replace from env vars..."

find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_TARA_CONNECTOR_ADDRESS_STRING_REPLACE,$TARA_CONNECTOR_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_ETH_CONNECTOR_ADDRESS_STRING_REPLACE,$ETH_CONNECTOR_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_TARA_ERC20_MINTING_CONNECTOR_ADDRESS_STRING_REPLACE,$TARA_ERC20_MINTING_CONNECTOR_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_ETH_ERC20_MINTING_CONNECTOR_ADDRESS_STRING_REPLACE,$ETH_ERC20_MINTING_CONNECTOR_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_ETH_BRIDGE_ADDRESS_STRING_REPLACE,$ETH_BRIDGE_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_TARA_BRIDGE_ADDRESS_STRING_REPLACE,$TARA_BRIDGE_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_WTARA_TOKEN_ADDRESS_STRING_REPLACE,$WTARA_TOKEN_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_WETH_TOKEN_ADDRESS_STRING_REPLACE,$WETH_TOKEN_ADDRESS,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_ETHEREUM_GRAPHQL_API_STRING_REPLACE,$ETHEREUM_GRAPHQL_API,g" {} \;
find $STATIC_FOLDER -type f -exec sed -i "s,NEXT_PUBLIC_TARAXA_GRAPHQL_API_STRING_REPLACE,$TARAXA_GRAPHQL_API,g" {} \;

exec "$@"
